import Head from "next/head";
import "./globals.css";
import "../styles/animations.css";
import { Poppins } from "next/font/google";
import { LanguageProvider } from "@/providers/LanguageProvider";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Daniel González Tormo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/images/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/images/favicon-16x16.png"
        />
        <title>Daniel González Tormo</title>
      </Head>
      <body className={`${poppins.className} overflow-x-hidden`}>
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
